export const CHANGE_TOWN_FIELD = 'CHANGE_TOWN_FIELD';
export const FETCH_TOWN_REQUEST = 'FETCH_TOWN_REQUEST';
export const FETCH_TOWN_SUCCESS = 'FETCH_TOWN_SUCCESS';
export const FETCH_TOWN_FAILURE = 'FETCH_TOWN_FAILURE';
